#!/usr/bin/env python3

# This file serves to bootstrap the zipfix executable. It performs version
# checks, and loads the real zipfix module onto PATH.
#
# This file should be executable with most versions of python 2 & 3, however
# zipfix requires python 3.6 to run.

import os
import sys


# This particular file shouldn't be included. Include the library instead.
if __name__ != '__main__':
    raise RuntimeError('git-zipfix must be run as __main__')


def upgrade_py(exe):
    assert os.path.dirname(sys.executable) != exe
    os.execvp(exe, [exe] + sys.argv[:])
    raise RuntimeError('execvp failed')


# Perform basic python version checking, and attempt to locate a sufficiently
# modern python interpreter.
try:
    ver = sys.version_info
    if ver[0] < 3:
        upgrade_py('python3')
    elif ver[0] == 3 and ver[1] < 6:
        upgrade_py('python3.6')
except FileNotFoundError:
    sys.stderr.write("error: zipfix requires Python >= 3.6 on $PATH\n")
    sys.stderr.write("  current executable: %s\n" % sys.executable)
    sys.stderr.write("  current version: %s\n" % sys.version)
    sys.exit(101)


# Add zipfix to the syspath, and load the module.
libpath = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, libpath)

import zipfix
zipfix.main(sys.argv[1:])
